// src/components/Greeting.jsx
import { useState } from 'preact/hooks';

export default function Greeting({ messages }) {
  const randomMessage = () =>
    messages[Math.floor(Math.random() * messages.length)];
  const [greeting, setGreeting] = useState(messages[0]);

  return (
    <dialog open>
      <article>
        <header>
          <button aria-label="Close" rel="prev"></button>
          <h3>
            <strong>{greeting}!  Thank You for Visiting!</strong>
          </h3>
        </header>
        <button onClick={() => setGreeting(randomMessage())}>
          New Greeting
        </button>
      </article>
    </dialog>
  );
}

// src/components/Greeting.svelte
<script>
  export let messages;

  import { onMount } from 'svelte';
  let greeting = messages[0];

  const randomMessage = () => {
    const randomIndex = Math.floor(Math.random() * messages.length);
    greeting = messages[randomIndex];
  };

  onMount(() => {
    randomMessage();
  });
</script>

<dialog open>
  <article>
    <header>
      <button aria-label="Close" rel="prev"></button>
      <h3><strong>{greeting}! Thank You for Visiting!</strong></h3>
    </header>
    <button onClick={randomMessage}> New Greeting </button>
  </article>
</dialog>
